=== adila01/banking-api/schemas/transfers/transfer_member.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "http://jsonschema.net",
  "required": true,
  "properties": {
    "sourceAccount_id": {
      "type": "string",
      "required": true
      },
    "targetAccount_id": {
      "type": "string",
      "required": true
      },
    "amount": {
      "type": "number",
      "required": true
    },
    "description": {
      "type": "string",
      "required": false
      }
    }
}

=== adila01/banking-api/examples/transfers_out.json
[
  { 
    "sourceAccount_id" : "a2esd212343123",
    "targetAccount_id" : "3523djfg329548",
    "amount": 1000.00,
    "description": "A written description of the transaction, provided at creation."
  },
  { 
    "sourceAccount_id" : "a2esd212343123",
    "targetAccount_id" : "3523djfg123123",
    "amount": 1024.00,
    "description": "This is the other description, again provided at creation."
  }
]
